### ISSUE TITLE
一键打包报错,这个改怎么解决

### ISSUE THREAD

**Issue by liujianying** [Hanks10100/weex-pack#6]
``` html
delalu:Desktop liujianying$ weexpack init TestWeepack
/usr/local/lib/node_modules/.weexpack_npminstall/node_modules/.0.0.1@weexpack/src/init/init.js:10
class SilentTerminalAdapter extends TerminalAdapter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/.weexpack_npminstall/node_modules/.0.0.1@weexpack/bin/weexpack-init:5:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

**Comment by Hanks10100** [comment]
你好，此项目还在开发过程中，功能还不完善，建议等我们开发完成后再使用。

此外，项目已经迁移到 [weex-pack](https://github.com/weexteam/weex-pack) 。

**Comment by walleeeee** [comment]
是不是你的node版本太低了

**Comment by Hanks10100** [comment]
项目已经迁移到 https://github.com/weexteam/weex-pack ，我这里代码不是最新的。
