### ISSUE TITLE
weexpack build web 指令报错

### ISSUE THREAD

**Issue by walid1992** [Hanks10100/weex-pack#8]
/usr/local/lib/node_modules/weexpack/src/build/web.js:16
  buildPlugin().then(() => {
               ^

TypeError: Cannot read property 'then' of undefined
    at buildWeb (/usr/local/lib/node_modules/weexpack/src/build/web.js:16:16)
    at build (/usr/local/lib/node_modules/weexpack/bin/weexpack-build:44:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/weexpack/bin/weexpack-build:56:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)

**Comment by JackPu** [comment]
@walid1992  这个问题已经修复了，但是版本没有提交上去，你用新的包就可以了。
